const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnimFrame
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{LiteTween: 0},
	{judul: 0},
	{ukuranx: 0},
	{ukurany: 0},
	{Tween: 0},
	{login: 0},
	{Sine: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Touch: 0},
	{bg2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{bgmateri1: 0},
	{materi1: 0},
	{next: 0},
	{prev: 0},
	{materii3: 0},
	{materi3: 0},
	{bgquiz: 0},
	{quiz1: 0},
	{jawab1: 0},
	{jawabbenar1: 0},
	{jawab1c: 0},
	{jawab1d: 0},
	{video: 0},
	{quiz2: 0},
	{jwb21: 0},
	{jawab22: 0},
	{jawab23: 0},
	{jawab24: 0},
	{quiz3: 0},
	{jwb31: 0},
	{jawab32: 0},
	{jawab33: 0},
	{jawab34: 0},
	{quiz4: 0},
	{jwb41: 0},
	{jawab42: 0},
	{jawab43: 0},
	{jawab44: 0},
	{quiz5: 0},
	{jawab51: 0},
	{jawab52: 0},
	{jawab53: 0},
	{jawab54: 0},
	{quiz7: 0},
	{jawab7a: 0},
	{jawab7b: 0},
	{jawab7c: 0},
	{jawab7d: 0},
	{quiz6: 0},
	{jawab6a: 0},
	{jawab6b: 0},
	{jawab6c: 0},
	{jawab6d: 0},
	{quiz8: 0},
	{jawab81: 0},
	{jawab82: 0},
	{jawab83: 0},
	{jawab84: 0},
	{quiz9: 0},
	{jawab91: 0},
	{jawab92: 0},
	{jawab93: 0},
	{jawab94: 0},
	{quiz10: 0},
	{jawab101: 0},
	{jawab102: 0},
	{jawab103: 0},
	{jawab104: 0},
	{quiz11: 0},
	{jawab111: 0},
	{jawab112: 0},
	{jawab113: 0},
	{jawab114: 0},
	{quiz12: 0},
	{jawab121: 0},
	{jawab122: 0},
	{jawab123: 0},
	{jawab124: 0},
	{quiz13: 0},
	{jawab131: 0},
	{jawab132: 0},
	{jawab133: 0},
	{jawab134: 0},
	{quiz14: 0},
	{jawab141: 0},
	{jawab142: 0},
	{jawab143: 0},
	{jawab144: 0},
	{quiz15: 0},
	{jawab151: 0},
	{jawab152: 0},
	{jawab145: 0},
	{jawab154: 0},
	{jawab153: 0},
	{quiz16: 0},
	{jawab161: 0},
	{jawab155: 0},
	{jawab162: 0},
	{jawab163: 0},
	{jawab164: 0},
	{quiz17: 0},
	{jawab171: 0},
	{jawab172: 0},
	{jawab173: 0},
	{jawab174: 0},
	{quiz18: 0},
	{jawab181: 0},
	{jawab182: 0},
	{jawab183: 0},
	{jawab184: 0},
	{quiz19: 0},
	{jawab191: 0},
	{jawab192: 0},
	{jawab193: 0},
	{jawab194: 0},
	{quiz20: 0},
	{jawab201: 0},
	{jawab202: 0},
	{jawab203: 0},
	{jawab204: 0},
	{quiz21: 0},
	{jawab211: 0},
	{jawab212: 0},
	{jawab213: 0},
	{jawab214: 0},
	{quiz22: 0},
	{jawab221: 0},
	{jawab222: 0},
	{jawab223: 0},
	{jawab224: 0},
	{quiz23: 0},
	{jawab231: 0},
	{jawab232: 0},
	{jawab233: 0},
	{jawab234: 0},
	{quiz24: 0},
	{jawab241: 0},
	{jawab242: 0},
	{jawab243: 0},
	{jawab244: 0},
	{quiz25: 0},
	{jawab251: 0},
	{jawab252: 0},
	{jawab253: 0},
	{jawab254: 0},
	{quiz26: 0},
	{jawab261: 0},
	{jawab262: 0},
	{jawab263: 0},
	{jawab264: 0},
	{quiz27: 0},
	{jawab271: 0},
	{jawab272: 0},
	{jawab273: 0},
	{jawab274: 0},
	{quiz28: 0},
	{jawab281: 0},
	{jawab282: 0},
	{jawab283: 0},
	{jawab284: 0},
	{quiz29: 0},
	{jawab291: 0},
	{jawab292: 0},
	{jawab293: 0},
	{jawab294: 0},
	{quiz30: 0},
	{jawab301: 0},
	{jawab302: 0},
	{jawab303: 0},
	{jawab304: 0},
	{jawab311: 0},
	{jawab312: 0},
	{jawab313: 0},
	{jawab314: 0},
	{quiz32: 0},
	{jawab321: 0},
	{jawab322: 0},
	{jawab323: 0},
	{jawab324: 0},
	{quiz33: 0},
	{jawab331: 0},
	{jawab332: 0},
	{jawab333: 0},
	{jawab334: 0},
	{quiz34: 0},
	{jawab341: 0},
	{jawab342: 0},
	{jawab343: 0},
	{jawab344: 0},
	{quiz35: 0},
	{jawab351: 0},
	{jawab352: 0},
	{jawab353: 0},
	{jawab354: 0},
	{quiz31: 0},
	{quiz36: 0},
	{quiz37: 0},
	{quiz2rev: 0},
	{Sprite9: 0},
	{bg3: 0},
	{bgMateri3: 0},
	{bgmateri4: 0},
	{bgmateri5: 0},
	{bgmateri6: 0},
	{bgmateri7: 0},
	{bgmateri8: 0},
	{Adeline: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{papansskor: 0},
	{Textskor: 0},
	{backskor: 0},
	{Audio: 0},
	{Video2: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite33: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Sprite50: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Sprite60: 0},
	{Sprite61: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{Sprite64: 0},
	{Sprite65: 0},
	{Sprite66: 0},
	{Sprite67: 0},
	{nomateri: 0},
	{nomateri2: 0},
	{nomateri3: 0},
	{nomateri4: 0},
	{nomateri5: 0},
	{nomateri6: 0},
	{nomateri7: 0},
	{nomateri8: 0},
	{nomateri9: 0},
	{popup: 0},
	{KOTAKOK: 0},
	{POPUP2: 0},
	{KOTAKOK2: 0},
	{KOTAKOK3: 0},
	{RU: 0},
	{KOTAKOK4: 0},
	{pause: 0},
	{pay: 0},
	{forward: 0},
	{backward: 0},
	{si: 0},
	{Textbenar: 0},
	{Textbenar2: 0},
	{satext: 0},
	{skor: 0},
	{benar: 0},
	{salah: 0},
	{lagu: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	judul: class extends self.ISpriteInstance {},
	login: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	bg2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	bgmateri1: class extends self.ISpriteInstance {},
	materi1: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	prev: class extends self.ISpriteInstance {},
	materii3: class extends self.ISpriteInstance {},
	materi3: class extends self.ISpriteInstance {},
	bgquiz: class extends self.ISpriteInstance {},
	quiz1: class extends self.ISpriteInstance {},
	jawab1: class extends self.ISpriteInstance {},
	jawabbenar1: class extends self.ISpriteInstance {},
	jawab1c: class extends self.ISpriteInstance {},
	jawab1d: class extends self.ISpriteInstance {},
	video: class extends self.ISpriteInstance {},
	quiz2: class extends self.ISpriteInstance {},
	jwb21: class extends self.ISpriteInstance {},
	jawab22: class extends self.ISpriteInstance {},
	jawab23: class extends self.ISpriteInstance {},
	jawab24: class extends self.ISpriteInstance {},
	quiz3: class extends self.ISpriteInstance {},
	jwb31: class extends self.ISpriteInstance {},
	jawab32: class extends self.ISpriteInstance {},
	jawab33: class extends self.ISpriteInstance {},
	jawab34: class extends self.ISpriteInstance {},
	quiz4: class extends self.ISpriteInstance {},
	jwb41: class extends self.ISpriteInstance {},
	jawab42: class extends self.ISpriteInstance {},
	jawab43: class extends self.ISpriteInstance {},
	jawab44: class extends self.ISpriteInstance {},
	quiz5: class extends self.ISpriteInstance {},
	jawab51: class extends self.ISpriteInstance {},
	jawab52: class extends self.ISpriteInstance {},
	jawab53: class extends self.ISpriteInstance {},
	jawab54: class extends self.ISpriteInstance {},
	quiz7: class extends self.ISpriteInstance {},
	jawab7a: class extends self.ISpriteInstance {},
	jawab7b: class extends self.ISpriteInstance {},
	jawab7c: class extends self.ISpriteInstance {},
	jawab7d: class extends self.ISpriteInstance {},
	quiz6: class extends self.ISpriteInstance {},
	jawab6a: class extends self.ISpriteInstance {},
	jawab6b: class extends self.ISpriteInstance {},
	jawab6c: class extends self.ISpriteInstance {},
	jawab6d: class extends self.ISpriteInstance {},
	quiz8: class extends self.ISpriteInstance {},
	jawab81: class extends self.ISpriteInstance {},
	jawab82: class extends self.ISpriteInstance {},
	jawab83: class extends self.ISpriteInstance {},
	jawab84: class extends self.ISpriteInstance {},
	quiz9: class extends self.ISpriteInstance {},
	jawab91: class extends self.ISpriteInstance {},
	jawab92: class extends self.ISpriteInstance {},
	jawab93: class extends self.ISpriteInstance {},
	jawab94: class extends self.ISpriteInstance {},
	quiz10: class extends self.ISpriteInstance {},
	jawab101: class extends self.ISpriteInstance {},
	jawab102: class extends self.ISpriteInstance {},
	jawab103: class extends self.ISpriteInstance {},
	jawab104: class extends self.ISpriteInstance {},
	quiz11: class extends self.ISpriteInstance {},
	jawab111: class extends self.ISpriteInstance {},
	jawab112: class extends self.ISpriteInstance {},
	jawab113: class extends self.ISpriteInstance {},
	jawab114: class extends self.ISpriteInstance {},
	quiz12: class extends self.ISpriteInstance {},
	jawab121: class extends self.ISpriteInstance {},
	jawab122: class extends self.ISpriteInstance {},
	jawab123: class extends self.ISpriteInstance {},
	jawab124: class extends self.ISpriteInstance {},
	quiz13: class extends self.ISpriteInstance {},
	jawab131: class extends self.ISpriteInstance {},
	jawab132: class extends self.ISpriteInstance {},
	jawab133: class extends self.ISpriteInstance {},
	jawab134: class extends self.ISpriteInstance {},
	quiz14: class extends self.ISpriteInstance {},
	jawab141: class extends self.ISpriteInstance {},
	jawab142: class extends self.ISpriteInstance {},
	jawab143: class extends self.ISpriteInstance {},
	jawab144: class extends self.ISpriteInstance {},
	quiz15: class extends self.ISpriteInstance {},
	jawab151: class extends self.ISpriteInstance {},
	jawab152: class extends self.ISpriteInstance {},
	jawab145: class extends self.ISpriteInstance {},
	jawab154: class extends self.ISpriteInstance {},
	jawab153: class extends self.ISpriteInstance {},
	quiz16: class extends self.ISpriteInstance {},
	jawab161: class extends self.ISpriteInstance {},
	jawab155: class extends self.ISpriteInstance {},
	jawab162: class extends self.ISpriteInstance {},
	jawab163: class extends self.ISpriteInstance {},
	jawab164: class extends self.ISpriteInstance {},
	quiz17: class extends self.ISpriteInstance {},
	jawab171: class extends self.ISpriteInstance {},
	jawab172: class extends self.ISpriteInstance {},
	jawab173: class extends self.ISpriteInstance {},
	jawab174: class extends self.ISpriteInstance {},
	quiz18: class extends self.ISpriteInstance {},
	jawab181: class extends self.ISpriteInstance {},
	jawab182: class extends self.ISpriteInstance {},
	jawab183: class extends self.ISpriteInstance {},
	jawab184: class extends self.ISpriteInstance {},
	quiz19: class extends self.ISpriteInstance {},
	jawab191: class extends self.ISpriteInstance {},
	jawab192: class extends self.ISpriteInstance {},
	jawab193: class extends self.ISpriteInstance {},
	jawab194: class extends self.ISpriteInstance {},
	quiz20: class extends self.ISpriteInstance {},
	jawab201: class extends self.ISpriteInstance {},
	jawab202: class extends self.ISpriteInstance {},
	jawab203: class extends self.ISpriteInstance {},
	jawab204: class extends self.ISpriteInstance {},
	quiz21: class extends self.ISpriteInstance {},
	jawab211: class extends self.ISpriteInstance {},
	jawab212: class extends self.ISpriteInstance {},
	jawab213: class extends self.ISpriteInstance {},
	jawab214: class extends self.ISpriteInstance {},
	quiz22: class extends self.ISpriteInstance {},
	jawab221: class extends self.ISpriteInstance {},
	jawab222: class extends self.ISpriteInstance {},
	jawab223: class extends self.ISpriteInstance {},
	jawab224: class extends self.ISpriteInstance {},
	quiz23: class extends self.ISpriteInstance {},
	jawab231: class extends self.ISpriteInstance {},
	jawab232: class extends self.ISpriteInstance {},
	jawab233: class extends self.ISpriteInstance {},
	jawab234: class extends self.ISpriteInstance {},
	quiz24: class extends self.ISpriteInstance {},
	jawab241: class extends self.ISpriteInstance {},
	jawab242: class extends self.ISpriteInstance {},
	jawab243: class extends self.ISpriteInstance {},
	jawab244: class extends self.ISpriteInstance {},
	quiz25: class extends self.ISpriteInstance {},
	jawab251: class extends self.ISpriteInstance {},
	jawab252: class extends self.ISpriteInstance {},
	jawab253: class extends self.ISpriteInstance {},
	jawab254: class extends self.ISpriteInstance {},
	quiz26: class extends self.ISpriteInstance {},
	jawab261: class extends self.ISpriteInstance {},
	jawab262: class extends self.ISpriteInstance {},
	jawab263: class extends self.ISpriteInstance {},
	jawab264: class extends self.ISpriteInstance {},
	quiz27: class extends self.ISpriteInstance {},
	jawab271: class extends self.ISpriteInstance {},
	jawab272: class extends self.ISpriteInstance {},
	jawab273: class extends self.ISpriteInstance {},
	jawab274: class extends self.ISpriteInstance {},
	quiz28: class extends self.ISpriteInstance {},
	jawab281: class extends self.ISpriteInstance {},
	jawab282: class extends self.ISpriteInstance {},
	jawab283: class extends self.ISpriteInstance {},
	jawab284: class extends self.ISpriteInstance {},
	quiz29: class extends self.ISpriteInstance {},
	jawab291: class extends self.ISpriteInstance {},
	jawab292: class extends self.ISpriteInstance {},
	jawab293: class extends self.ISpriteInstance {},
	jawab294: class extends self.ISpriteInstance {},
	quiz30: class extends self.ISpriteInstance {},
	jawab301: class extends self.ISpriteInstance {},
	jawab302: class extends self.ISpriteInstance {},
	jawab303: class extends self.ISpriteInstance {},
	jawab304: class extends self.ISpriteInstance {},
	jawab311: class extends self.ISpriteInstance {},
	jawab312: class extends self.ISpriteInstance {},
	jawab313: class extends self.ISpriteInstance {},
	jawab314: class extends self.ISpriteInstance {},
	quiz32: class extends self.ISpriteInstance {},
	jawab321: class extends self.ISpriteInstance {},
	jawab322: class extends self.ISpriteInstance {},
	jawab323: class extends self.ISpriteInstance {},
	jawab324: class extends self.ISpriteInstance {},
	quiz33: class extends self.ISpriteInstance {},
	jawab331: class extends self.ISpriteInstance {},
	jawab332: class extends self.ISpriteInstance {},
	jawab333: class extends self.ISpriteInstance {},
	jawab334: class extends self.ISpriteInstance {},
	quiz34: class extends self.ISpriteInstance {},
	jawab341: class extends self.ISpriteInstance {},
	jawab342: class extends self.ISpriteInstance {},
	jawab343: class extends self.ISpriteInstance {},
	jawab344: class extends self.ISpriteInstance {},
	quiz35: class extends self.ISpriteInstance {},
	jawab351: class extends self.ISpriteInstance {},
	jawab352: class extends self.ISpriteInstance {},
	jawab353: class extends self.ISpriteInstance {},
	jawab354: class extends self.ISpriteInstance {},
	quiz31: class extends self.ISpriteInstance {},
	quiz36: class extends self.ISpriteInstance {},
	quiz37: class extends self.ISpriteInstance {},
	quiz2rev: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	bg3: class extends self.ISpriteInstance {},
	bgMateri3: class extends self.ISpriteInstance {},
	bgmateri4: class extends self.ISpriteInstance {},
	bgmateri5: class extends self.ISpriteInstance {},
	bgmateri6: class extends self.ISpriteInstance {},
	bgmateri7: class extends self.ISpriteInstance {},
	bgmateri8: class extends self.ISpriteInstance {},
	Adeline: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	papansskor: class extends self.ISpriteInstance {},
	Textskor: class extends self.ITextInstance {},
	backskor: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Video2: class extends self.IWorldInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	nomateri: class extends self.ISpriteInstance {},
	nomateri2: class extends self.ISpriteInstance {},
	nomateri3: class extends self.ISpriteInstance {},
	nomateri4: class extends self.ISpriteInstance {},
	nomateri5: class extends self.ISpriteInstance {},
	nomateri6: class extends self.ISpriteInstance {},
	nomateri7: class extends self.ISpriteInstance {},
	nomateri8: class extends self.ISpriteInstance {},
	nomateri9: class extends self.ISpriteInstance {},
	popup: class extends self.ISpriteInstance {},
	KOTAKOK: class extends self.ISpriteInstance {},
	POPUP2: class extends self.ISpriteInstance {},
	KOTAKOK2: class extends self.ISpriteInstance {},
	KOTAKOK3: class extends self.ISpriteInstance {},
	RU: class extends self.ISpriteInstance {},
	KOTAKOK4: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	pay: class extends self.ISpriteInstance {},
	forward: class extends self.ISpriteInstance {},
	backward: class extends self.ISpriteInstance {},
	si: class extends self.ISpriteInstance {},
	Textbenar: class extends self.ITextInstance {},
	Textbenar2: class extends self.ITextInstance {},
	satext: class extends self.ITextInstance {}
}